### ISSUE TITLE
Artefact with no text/inscription

### ISSUE THREAD

**Issue by lettychardon** [SunoikisisDC/SunoikisisDC-2021-2022#10]
If we are doing an object with no written text/inscription, do we just leave all those sections of the document empty or do we need to remove the tags? Thank you!

**Comment by gabrielbodard** [comment]
As discussed in the seminar yesterday, there's no single answer to this question—it depends on what the stylesheet that is rendering and otherwise processing the EpiDoc expects to see. Try both and see if it makes any difference in EFES?

Certainly if you are encoding an entire corpus of objects within text information such as `<layoutDesc>`, `<handDesc>` etc in your records, then you should just leave those whole sections out of your template so you don't need worry about them. The same is true of (almost) anything else in your XML: if you don't need it, you can leave it out. And the converse: if you need something that isn't in the template but the schema allows—add it; if you need something to be repeated, that's usually fine too.
